# For more information about the configurations used
# in this file, please see the Travis CI documentation.
# .travis.yml
# https://docs.travis-ci.com

os: osx
sudo: true
osx_image: xcode12.2
language: shell

env:
  global:
  - NONINTERACTIVE=1
  - HOMEBREW_NO_AUTO_UPDATE=true
  - HOMEBREW_INSTALL_BADGE="☕️ 🐸"
  - HOMEBREW_CASK_OPTS="--appdir=/Applications"

addons:
  homebrew:
    update: true

install:
  - echo | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  - bash -c "./src/os/mac_setup.sh --force"

notifications:
  email:
    on_failure: never
    on_success: never
