# For more information about the configurations used
# in this file, please see the Travis CI documentation.
# .travis.yml
# https://docs.travis-ci.com

env:
  global:
  - NONINTERACTIVE="1"
  - HOMEBREW_NO_AUTO_UPDATE="true"
  - HOMEBREW_INSTALL_BADGE="☕️ 🐸"
  - HOMEBREW_CASK_OPTS="--appdir=/Applications"

os: osx
sudo: true
osx_image: xcode12.1
language: shell

before_install:
  - echo | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  - brew update -f && brew upgrade -f

install:
  - bash -c "./src/os/mac_setup.sh"

notifications:
  email:
    on_failure: never
    on_success: never
