# For more information about the configurations used
# in this file, please see the Travis CI documentation.
# .travis.yml
# https://docs.travis-ci.com

os: osx
sudo: true
osx_image: xcode11.6
language: shell

install:
  - bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  - bash -c "$(curl -LsS https://github.com/casjay-systems/macos/raw/master/install.sh)"

notifications:
  email:
    on_failure: never
    on_success: never
