# For more information about the configurations used
# in this file, please see the Travis CI documentation.
# .travis.yml
# https://docs.travis-ci.com

os: osx
sudo: true
osx_image: xcode12.2
language: shell
#before_install: brew update -f ; brew upgrade -f

install:
  - bash -c "./src/os/mac_setup.sh --force"

notifications:
  email:
    on_failure: never
    on_success: never
