#!/usr/bin/env bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# If not running interactively, don't do anything

case $- in
*i*) ;;
*) return ;;
esac

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

#source users functions

userbashfunctions() {
  local d=$(ls "$HOME"/.config/bash/functions/*.bash 2>/dev/null | wc -l)
  if [ "$d" != "0" ]; then
    for f in "$HOME"/.config/bash/functions/*.bash; do
      source "$f"
    done
  fi
}

userbashfunctions

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

#ensure the exports get loaded

userbashexports() {
  local d=$(ls "$HOME"/.config/bash/exports/*.bash 2>/dev/null | wc -l)
  if [ "$d" != "0" ]; then
    for f in "$HOME"/.config/bash/exports/*.bash; do
      source "$f" >/dev/null 2>&1
    done
  fi
}

userbashexports

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Source additional bash scripts

userbashprofile() {
  local d=$(ls "$HOME"/.config/bash/profile/*.bash 2>/dev/null | wc -l)
  if [ "$d" != "0" ]; then
    for f in "$HOME"/.config/bash/profile/*.bash; do
      source "$f" >/dev/null 2>&1
    done
  fi
}

userbashprofile

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Source additional aliases scripts

userbashaliases() {
  local d=$(ls "$HOME"/.config/bash/aliases/*.bash 2>/dev/null | wc -l)
  if [ "$d" != "0" ]; then
    for f in "$HOME"/.config/bash/aliases/*.bash; do
      source "$f" >/dev/null 2>&1
    done
  fi
}

userbashaliases

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Source additional completion scripts

userbashcompletions() {
  local d=$(ls "$HOME"/.config/bash/completions/*.bash 2>/dev/null | wc -l)
  if [ "$d" != "0" ]; then
    for f in "$HOME"/.config/bash/completions/*.bash; do
      source "$f" >/dev/null 2>&1
    done
  fi
}

userbashcompletions

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Source additional user bash scripts

userbashprofilelocal() {
  local d=$(ls "$HOME"/.config/bash/local/*.bash 2>/dev/null | wc -l)
  if [ "$d" != "0" ]; then
    for f in "$HOME"/.config/bash/local/*.bash; do
      source "$f" >/dev/null 2>&1
    done
  fi
}

userbashprofilelocal

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

show_welcome

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# run neofetch
#if echo "$-" | grep i > /dev/null; then
# if [ -f /usr/bin/neofetch ];
#    then /usr/bin/neofetch
# fi
#fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Send an e-mail every time you login

#echo "ALERT - Shell Access on $HOSTNAME from $USER on: `date`" | mail -r no-reply -s "Alert: Access from $USER" $USER@$HOSTNAME

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# end
#/* vim set expandtab ts=2 noai :
